server:
  port: 80

spring:
  application:
    name: cloud-order-server

eureka:
  client:
    register-with-eureka: false   #注册自己的配置:默认也是true
    fetch-registry: true #自己就是注册中心，维护服务实例，不去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/

ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间，5s
  ConnectTimeout: 5000

logging:
  level:
    #feign以什么级别监控哪个接口
    com.guigu.springcloud.service.PaymentFeignService: debug