server:
  port: 83

spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

#为了使用resttemplete调用时不用再写服务名
server-url:
  nacos-user-service: http://nacos-provider-payment